/*
  Decorative calendar-stone wheel served as a static, cacheable asset
  (public/tzolkin-wheel.svg, generated by tmp/gen-wheel-svg.mjs).
  Keeping it out of the markup avoids inflating every page's HTML/RSC payload.
*/
export default function TzolkinWheel({ className = "" }: { className?: string }) {
  return (
    // eslint-disable-next-line @next/next/no-img-element
    <img src="/tzolkin-wheel.svg" alt="" aria-hidden="true" decoding="async" className={className} />
  );
}
