import type { Metadata } from 'next';
import Link from 'next/link';

export const metadata: Metadata = {
  title: 'Sample Personalized Mayan Birth Chart Report',
  description: 'Preview the structure and level of detail in a personalized Mayan birth chart PDF report.',
  robots: {
    index: false,
    follow: false,
  },
};

const contents = [
  'Signature at a Glance',
  'Your Nawal in Depth',
  'Your Galactic Tone in Depth',
  'Integrated Sign-and-Tone Reading',
  'Relationships and Communication',
  'Work, Creativity, and Purpose',
  'Stress and Balance',
  'Decision Filter',
  '7-Day Integration',
  'Methodology and Closing Reflection',
];

export default function SampleReportPage() {
  return (
    <div className="page-shell py-10 md:py-16">
      <main className="mx-auto max-w-5xl px-4 sm:px-6">
        <section className="mb-8 rounded-2xl border border-[var(--gold-line)] bg-[rgb(212_162_78/6%)] p-5 text-sm text-[var(--parchment-dim)]">
          <p className="font-semibold text-[var(--parchment)]">Anonymous sample preview</p>
          <p className="mt-1">
            This is a real, anonymous report generated by the same deterministic template used for paid
            orders. A purchased report uses the birth date submitted at checkout.
          </p>
          <a
            href="/samples/personal-mayan-signature-report-sample.pdf"
            target="_blank"
            rel="noopener noreferrer"
            className="mt-3 inline-block font-bold text-gold-bright underline underline-offset-4"
          >
            Open the complete 11-page PDF ↗
          </a>
        </section>

        <article className="panel panel-glow overflow-hidden rounded-3xl">
          <header className="bg-[linear-gradient(150deg,#451a03_0%,#7c2d12_50%,#450a0a_100%)] px-7 py-14 text-center text-white md:px-14 md:py-20 border-b border-[var(--gold-line-strong)]">
            <p className="mb-4 text-sm font-semibold uppercase tracking-[0.22em] text-gold-bright">
              Personalized Mayan Birth Chart
            </p>
            <h1 className="text-5xl font-display md:text-7xl">11 Ik</h1>
            <p className="mt-4 text-xl text-[#f6dc9f]">The Spectral Wind</p>
            <div className="mx-auto mt-9 grid max-w-xl grid-cols-2 gap-3 text-left text-sm md:grid-cols-4">
              {[
                ['Nawal', 'Ik'],
                ['Tone', '11 · Spectral'],
                ['Format', '11 pages'],
                ['Price', '$7 once'],
              ].map(([label, value]) => (
                <div key={label} className="rounded-xl border border-white/20 bg-black/20 p-4">
                  <p className="text-gold-bright">{label}</p>
                  <p className="mt-1 font-bold text-white">{value}</p>
                </div>
              ))}
            </div>
          </header>

          <div className="space-y-12 px-6 py-10 md:px-14 md:py-14">
            <section className="grid grid-cols-1 gap-8 md:grid-cols-[0.8fr_1.2fr]">
              <div>
                <p className="text-sm font-semibold uppercase tracking-wide text-gold-bright">At a glance</p>
                <h2 className="mt-2 text-3xl font-display text-[var(--parchment)]">What the full PDF contains</h2>
              </div>
              <ol className="grid grid-cols-1 gap-3 text-[var(--parchment-dim)] sm:grid-cols-2">
                {contents.map((item, index) => (
                  <li key={item} className="rounded-xl border border-[var(--gold-line)] bg-[var(--surface)] p-4">
                    <span className="mr-2 font-bold text-gold-bright">{String(index + 1).padStart(2, '0')}</span>
                    {item}
                  </li>
                ))}
              </ol>
            </section>

            <hr className="border-[var(--gold-line)]" />

            <section>
              <p className="text-sm font-semibold uppercase tracking-wide text-gold-bright">Sample section 01</p>
              <h2 className="mt-2 text-3xl font-display text-[var(--parchment)]">Your Mayan Signature</h2>
              <p className="mt-5 max-w-3xl text-lg leading-8 text-[var(--parchment-dim)]">
                In this example, Ik contributes themes of breath, communication, movement, and inspired
                speech. Tone 11 adds the rhythm of release, liberation, and simplification. The
                longer report explores where those two patterns reinforce each other and where they can
                create tension.
              </p>
              <div className="mt-7 grid grid-cols-1 gap-5 md:grid-cols-2">
                <div className="rounded-2xl border border-[rgb(79_209_165/25%)] bg-[rgb(79_209_165/6%)] p-6">
                  <h3 className="text-xl font-display text-[var(--parchment)]">Core gifts</h3>
                  <ul className="mt-4 space-y-2 text-[var(--parchment-dim)]">
                    <li>• Mediation and peacemaking</li>
                    <li>• Gentle, persistent leadership</li>
                    <li>• A strong instinct for fairness</li>
                    <li>• Calm presence in complex situations</li>
                  </ul>
                </div>
                <div className="rounded-2xl border border-[rgb(234_88_12/25%)] bg-[rgb(234_88_12/7%)] p-6">
                  <h3 className="text-xl font-display text-[var(--parchment)]">Growth edges</h3>
                  <ul className="mt-4 space-y-2 text-[var(--parchment-dim)]">
                    <li>• Avoiding conflict until pressure builds</li>
                    <li>• Quietly carrying too much responsibility</li>
                    <li>• Waiting for permission to lead</li>
                    <li>• Confusing peacekeeping with self-erasure</li>
                  </ul>
                </div>
              </div>
            </section>

            <section className="rounded-3xl border border-[var(--gold-line-strong)] bg-[linear-gradient(150deg,#1c1210,#0b0908)] p-7 text-white md:p-10 shadow-[0_24px_60px_-24px_rgb(0_0_0/70%)]">
              <p className="text-sm font-semibold uppercase tracking-wide text-gold-bright">Sample section 05</p>
              <h2 className="mt-2 text-3xl font-display">Relationships and Communication</h2>
              <p className="mt-5 max-w-3xl leading-7 text-[var(--parchment-dim)]">
                The relationship section examines how the sample signature may give support, communicate
                needs, respond to tension, and maintain boundaries. It includes both supportive tendencies
                and patterns that may become overused.
              </p>
              <div className="mt-7 grid grid-cols-1 gap-5 md:grid-cols-2">
                <div className="rounded-2xl border border-[var(--gold-line)] bg-[rgb(212_162_78/6%)] p-6">
                  <h3 className="font-display text-gold-bright">Reflective strength</h3>
                  <p className="mt-2 text-[var(--parchment-dim)]">Creating enough calm for an honest conversation to begin.</p>
                </div>
                <div className="rounded-2xl border border-[var(--gold-line)] bg-[rgb(212_162_78/6%)] p-6">
                  <h3 className="font-display text-gold-bright">Reflective question</h3>
                  <p className="mt-2 text-[var(--parchment-dim)]">Where would a direct request be healthier than silent support?</p>
                </div>
              </div>
            </section>

            <section>
              <p className="text-sm font-semibold uppercase tracking-wide text-gold-bright">Sample section 07</p>
              <h2 className="mt-2 text-3xl font-display text-[var(--parchment)]">Reflection and 7-Day Integration</h2>
              <p className="mt-4 max-w-3xl text-[var(--parchment-dim)]">
                Every report ends with questions and a short practice so the reading can be tested against
                lived experience rather than treated as a prediction.
              </p>
              <div className="mt-7 grid grid-cols-1 gap-3 sm:grid-cols-2 lg:grid-cols-3">
                {[
                  'Name one purpose you want to serve this week.',
                  'Notice where your body senses tension first.',
                  'Practice one honest sentence that preserves dignity.',
                  'Decline one responsibility that is not truly yours.',
                  'Offer support without taking control.',
                  'Reflect on where your presence created more harmony.',
                ].map((prompt, index) => (
                  <div key={prompt} className="rounded-xl border border-[var(--gold-line)] bg-[var(--surface)] p-5 text-[var(--parchment-dim)]">
                    <p className="text-sm font-bold text-gold-bright">Day {index + 1}</p>
                    <p className="mt-2">{prompt}</p>
                  </div>
                ))}
              </div>
            </section>

            <section className="rounded-2xl border border-[rgb(79_209_165/22%)] bg-[rgb(79_209_165/6%)] p-6 text-sm text-[var(--parchment-dim)]">
              <h2 className="font-display text-[var(--parchment)]">Methodology and scope</h2>
              <p className="mt-2">
                The Nawal and Galactic Tone are calculated deterministically from the submitted date. The
                longer passages are interpretive synthesis for reflection and self-discovery. They are not
                scientific findings or medical, legal, financial, or psychological advice.
              </p>
            </section>
          </div>
        </article>

        <section className="mt-10 text-center">
          <h2 className="text-3xl font-display text-[var(--parchment)]">See the report written for your signature</h2>
          <p className="mx-auto mt-3 max-w-2xl text-[var(--parchment-dim)]">
            Calculate your free Mayan result first. The report option will appear directly beneath your signature.
          </p>
          <Link
            href="/"
            className="mt-6 btn-ember inline-block px-7 py-3.5"
          >
            Calculate my Mayan signature
          </Link>
        </section>
      </main>
    </div>
  );
}
