import type { Metadata } from 'next';
import Link from 'next/link';

export const metadata: Metadata = {
  title: 'Sample Mayan Compatibility Report',
  description: 'Preview the structure and level of detail in a personalized Mayan compatibility PDF report for two birth dates.',
  robots: {
    index: false,
    follow: false,
  },
};

const contents = [
  'Pair map and relationship lens',
  'Person A in this pairing',
  'Person B in this pairing',
  'Tone rhythm and sequence',
  'Nawal chemistry and shared roles',
  'Friction and smallest repair moves',
  'Context-specific communication scripts',
  'Two-person decision filter',
  'Seven-day practice',
  'Methodology and closing reflection',
];

export default function SampleCompatibilityReportPage() {
  return (
    <div className="page-shell py-10 md:py-16">
      <main className="mx-auto max-w-5xl px-4 sm:px-6">
        <section className="mb-8 rounded-2xl border border-[var(--gold-line)] bg-[rgb(212_162_78/6%)] p-5 text-sm text-[var(--parchment-dim)]">
          <p className="font-semibold text-[var(--parchment)]">Anonymous sample preview</p>
          <p className="mt-1">
            This is a real, anonymous pair report generated by the same deterministic template used for
            paid compatibility orders. A purchased report uses the two birth dates and relationship
            context submitted at checkout.
          </p>
          <a
            href="/samples/mayan-compatibility-report-sample.pdf"
            target="_blank"
            rel="noopener noreferrer"
            className="mt-3 inline-block font-bold text-gold-bright underline underline-offset-4"
          >
            Open the complete 11-page PDF ↗
          </a>
        </section>

        <article className="panel panel-glow overflow-hidden rounded-3xl">
          <header className="bg-[linear-gradient(150deg,#451a03_0%,#7c2d12_50%,#450a0a_100%)] px-7 py-14 text-center text-white md:px-14 md:py-20 border-b border-[var(--gold-line-strong)]">
            <p className="mb-4 text-sm font-semibold uppercase tracking-[0.22em] text-gold-bright">
              Mayan Compatibility Report
            </p>
            <h1 className="text-4xl font-display md:text-6xl">11 Ik + 4 Ahau</h1>
            <p className="mt-4 text-xl text-[#f6dc9f]">A romantic pair reading</p>
            <div className="mx-auto mt-9 grid max-w-xl grid-cols-2 gap-3 text-left text-sm md:grid-cols-4">
              {[
                ['Person A', '11 Ik'],
                ['Person B', '4 Ahau'],
                ['Format', '11 pages'],
                ['Price', '$12 once'],
              ].map(([label, value]) => (
                <div key={label} className="rounded-xl border border-white/20 bg-black/20 p-4">
                  <p className="text-gold-bright">{label}</p>
                  <p className="mt-1 font-bold text-white">{value}</p>
                </div>
              ))}
            </div>
          </header>

          <div className="space-y-12 px-6 py-10 md:px-14 md:py-14">
            <section className="grid grid-cols-1 gap-8 md:grid-cols-[0.8fr_1.2fr]">
              <div>
                <p className="text-sm font-semibold uppercase tracking-wide text-gold-bright">At a glance</p>
                <h2 className="mt-2 text-3xl font-display text-[var(--parchment)]">What the full PDF contains</h2>
              </div>
              <ol className="grid grid-cols-1 gap-3 text-[var(--parchment-dim)] sm:grid-cols-2">
                {contents.map((item, index) => (
                  <li key={item} className="rounded-xl border border-[var(--gold-line)] bg-[var(--surface)] p-4">
                    <span className="mr-2 font-bold text-gold-bright">{String(index + 1).padStart(2, '0')}</span>
                    {item}
                  </li>
                ))}
              </ol>
            </section>

            <hr className="border-[var(--gold-line)]" />

            <section>
              <p className="text-sm font-semibold uppercase tracking-wide text-gold-bright">Sample section 03</p>
              <h2 className="mt-2 text-3xl font-display text-[var(--parchment)]">Tone rhythm</h2>
              <p className="mt-5 max-w-3xl text-lg leading-8 text-[var(--parchment-dim)]">
                In this example, Tone 11 Spectral and Tone 4 Self-Existing sit far enough apart that one
                person may be releasing a cycle while the other is giving the bond a usable shape. The
                paid report treats that as a sequence problem, not a verdict about who is “too much.”
              </p>
            </section>

            <section className="rounded-3xl border border-[var(--gold-line-strong)] bg-[linear-gradient(150deg,#1c1210,#0b0908)] p-7 text-white md:p-10 shadow-[0_24px_60px_-24px_rgb(0_0_0/70%)]">
              <p className="text-sm font-semibold uppercase tracking-wide text-gold-bright">Sample section 06</p>
              <h2 className="mt-2 text-3xl font-display">Closer conversation</h2>
              <p className="mt-5 max-w-3xl leading-7 text-[var(--parchment-dim)]">
                The romantic version names who reaches, who waits, and what counts as care. Friendship and
                work versions use the same pair calculation, but the scripts and seven-day practice change.
              </p>
            </section>

            <section className="rounded-2xl border border-[rgb(79_209_165/22%)] bg-[rgb(79_209_165/6%)] p-6 text-sm text-[var(--parchment-dim)]">
              <h2 className="font-display text-[var(--parchment)]">Methodology and scope</h2>
              <p className="mt-2">
                The score is calculated from the two dates only. The relationship context changes the
                interpretive language, not the number. The longer passages are modern reflective
                synthesis. They are not scientific findings or medical, legal, financial, or psychological advice.
              </p>
            </section>
          </div>
        </article>

        <section className="mt-10 text-center">
          <h2 className="text-3xl font-display text-[var(--parchment)]">See the report written for your pair</h2>
          <p className="mx-auto mt-3 max-w-2xl text-[var(--parchment-dim)]">
            Calculate a free compatibility reading first. The pair-report option appears directly beneath the result.
          </p>
          <Link href="/compatibility" className="mt-6 btn-ember inline-block px-7 py-3.5">
            Compare two birth dates
          </Link>
        </section>
      </main>
    </div>
  );
}
